export const canonicalBooks = [
  { id: "genesis", name: "Genesis", testament: "Old", bookOrder: 1, chapterCount: 50 },
  { id: "exodus", name: "Exodus", testament: "Old", bookOrder: 2, chapterCount: 40 },
  { id: "leviticus", name: "Leviticus", testament: "Old", bookOrder: 3, chapterCount: 27 },
  { id: "numbers", name: "Numbers", testament: "Old", bookOrder: 4, chapterCount: 36 },
  { id: "deuteronomy", name: "Deuteronomy", testament: "Old", bookOrder: 5, chapterCount: 34 },
  { id: "joshua", name: "Joshua", testament: "Old", bookOrder: 6, chapterCount: 24 },
  { id: "judges", name: "Judges", testament: "Old", bookOrder: 7, chapterCount: 21 },
  { id: "ruth", name: "Ruth", testament: "Old", bookOrder: 8, chapterCount: 4 },
  { id: "1-samuel", name: "1 Samuel", testament: "Old", bookOrder: 9, chapterCount: 31 },
  { id: "2-samuel", name: "2 Samuel", testament: "Old", bookOrder: 10, chapterCount: 24 },
  { id: "1-kings", name: "1 Kings", testament: "Old", bookOrder: 11, chapterCount: 22 },
  { id: "2-kings", name: "2 Kings", testament: "Old", bookOrder: 12, chapterCount: 25 },
  { id: "1-chronicles", name: "1 Chronicles", testament: "Old", bookOrder: 13, chapterCount: 29 },
  { id: "2-chronicles", name: "2 Chronicles", testament: "Old", bookOrder: 14, chapterCount: 36 },
  { id: "ezra", name: "Ezra", testament: "Old", bookOrder: 15, chapterCount: 10 },
  { id: "nehemiah", name: "Nehemiah", testament: "Old", bookOrder: 16, chapterCount: 13 },
  { id: "esther", name: "Esther", testament: "Old", bookOrder: 17, chapterCount: 10 },
  { id: "job", name: "Job", testament: "Old", bookOrder: 18, chapterCount: 42 },
  { id: "psalms", name: "Psalms", testament: "Old", bookOrder: 19, chapterCount: 150 },
  { id: "proverbs", name: "Proverbs", testament: "Old", bookOrder: 20, chapterCount: 31 },
  { id: "ecclesiastes", name: "Ecclesiastes", testament: "Old", bookOrder: 21, chapterCount: 12 },
  { id: "song-of-solomon", name: "Song of Solomon", testament: "Old", bookOrder: 22, chapterCount: 8 },
  { id: "isaiah", name: "Isaiah", testament: "Old", bookOrder: 23, chapterCount: 66 },
  { id: "jeremiah", name: "Jeremiah", testament: "Old", bookOrder: 24, chapterCount: 52 },
  { id: "lamentations", name: "Lamentations", testament: "Old", bookOrder: 25, chapterCount: 5 },
  { id: "ezekiel", name: "Ezekiel", testament: "Old", bookOrder: 26, chapterCount: 48 },
  { id: "daniel", name: "Daniel", testament: "Old", bookOrder: 27, chapterCount: 12 },
  { id: "hosea", name: "Hosea", testament: "Old", bookOrder: 28, chapterCount: 14 },
  { id: "joel", name: "Joel", testament: "Old", bookOrder: 29, chapterCount: 3 },
  { id: "amos", name: "Amos", testament: "Old", bookOrder: 30, chapterCount: 9 },
  { id: "obadiah", name: "Obadiah", testament: "Old", bookOrder: 31, chapterCount: 1 },
  { id: "jonah", name: "Jonah", testament: "Old", bookOrder: 32, chapterCount: 4 },
  { id: "micah", name: "Micah", testament: "Old", bookOrder: 33, chapterCount: 7 },
  { id: "nahum", name: "Nahum", testament: "Old", bookOrder: 34, chapterCount: 3 },
  { id: "habakkuk", name: "Habakkuk", testament: "Old", bookOrder: 35, chapterCount: 3 },
  { id: "zephaniah", name: "Zephaniah", testament: "Old", bookOrder: 36, chapterCount: 3 },
  { id: "haggai", name: "Haggai", testament: "Old", bookOrder: 37, chapterCount: 2 },
  { id: "zechariah", name: "Zechariah", testament: "Old", bookOrder: 38, chapterCount: 14 },
  { id: "malachi", name: "Malachi", testament: "Old", bookOrder: 39, chapterCount: 4 },
  { id: "matthew", name: "Matthew", testament: "New", bookOrder: 40, chapterCount: 28 },
  { id: "mark", name: "Mark", testament: "New", bookOrder: 41, chapterCount: 16 },
  { id: "luke", name: "Luke", testament: "New", bookOrder: 42, chapterCount: 24 },
  { id: "john", name: "John", testament: "New", bookOrder: 43, chapterCount: 21 },
  { id: "acts", name: "Acts", testament: "New", bookOrder: 44, chapterCount: 28 },
  { id: "romans", name: "Romans", testament: "New", bookOrder: 45, chapterCount: 16 },
  { id: "1-corinthians", name: "1 Corinthians", testament: "New", bookOrder: 46, chapterCount: 16 },
  { id: "2-corinthians", name: "2 Corinthians", testament: "New", bookOrder: 47, chapterCount: 13 },
  { id: "galatians", name: "Galatians", testament: "New", bookOrder: 48, chapterCount: 6 },
  { id: "ephesians", name: "Ephesians", testament: "New", bookOrder: 49, chapterCount: 6 },
  { id: "philippians", name: "Philippians", testament: "New", bookOrder: 50, chapterCount: 4 },
  { id: "colossians", name: "Colossians", testament: "New", bookOrder: 51, chapterCount: 4 },
  { id: "1-thessalonians", name: "1 Thessalonians", testament: "New", bookOrder: 52, chapterCount: 5 },
  { id: "2-thessalonians", name: "2 Thessalonians", testament: "New", bookOrder: 53, chapterCount: 3 },
  { id: "1-timothy", name: "1 Timothy", testament: "New", bookOrder: 54, chapterCount: 6 },
  { id: "2-timothy", name: "2 Timothy", testament: "New", bookOrder: 55, chapterCount: 4 },
  { id: "titus", name: "Titus", testament: "New", bookOrder: 56, chapterCount: 3 },
  { id: "philemon", name: "Philemon", testament: "New", bookOrder: 57, chapterCount: 1 },
  { id: "hebrews", name: "Hebrews", testament: "New", bookOrder: 58, chapterCount: 13 },
  { id: "james", name: "James", testament: "New", bookOrder: 59, chapterCount: 5 },
  { id: "1-peter", name: "1 Peter", testament: "New", bookOrder: 60, chapterCount: 5 },
  { id: "2-peter", name: "2 Peter", testament: "New", bookOrder: 61, chapterCount: 3 },
  { id: "1-john", name: "1 John", testament: "New", bookOrder: 62, chapterCount: 5 },
  { id: "2-john", name: "2 John", testament: "New", bookOrder: 63, chapterCount: 1 },
  { id: "3-john", name: "3 John", testament: "New", bookOrder: 64, chapterCount: 1 },
  { id: "jude", name: "Jude", testament: "New", bookOrder: 65, chapterCount: 1 },
  { id: "revelation", name: "Revelation", testament: "New", bookOrder: 66, chapterCount: 22 },
] as const;